# [START app_yaml]
runtime: nodejs
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
env_variables:
  SPANNER_ID: 'todo-spanner'
  PROJECT_ID: 'google.com:nc-ce-spanner'
# [END app_yaml]
